// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Block: typeof import('./components/editor/blocks/elements/block.vue')['default']
    BlockColor: typeof import('./components/editor/tools/BlockColor.vue')['default']
    BlockContainer: typeof import('./components/editor/blocks/BlockContainer.vue')['default']
    BlockCss: typeof import('./components/editor/tools/BlockCss.vue')['default']
    BlockEdit: typeof import('./components/editor/tools/BlockEdit.vue')['default']
    BlockElements: typeof import('./components/editor/tools/BlockElements.vue')['default']
    BlockFloatingBar: typeof import('./components/editor/blocks/BlockFloatingBar.vue')['default']
    BlockFont: typeof import('./components/editor/tools/BlockFont.vue')['default']
    BlockGrid: typeof import('./components/editor/tools/BlockGrid.vue')['default']
    BlockHeading: typeof import('./components/editor/tools/BlockHeading.vue')['default']
    BlockImage: typeof import('./components/editor/tools/BlockImage.vue')['default']
    BlockLink: typeof import('./components/editor/tools/BlockLink.vue')['default']
    BlockOption: typeof import('./components/editor/tools/BlockOption.vue')['default']
    BlockPadding: typeof import('./components/editor/tools/BlockPadding.vue')['default']
    BlockPreview: typeof import('./components/preview/BlockPreview.vue')['default']
    BlockSlider: typeof import('./components/editor/tools/BlockSlider.vue')['default']
    BlockSnippets: typeof import('./components/editor/tools/BlockSnippets.vue')['default']
    BlockTree: typeof import('./components/editor/tools/BlockTree.vue')['default']
    BlockWindi: typeof import('./components/editor/tools/BlockWindi.vue')['default']
    Chip: typeof import('./components/common/Chip.vue')['default']
    Container: typeof import('./components/editor/blocks/elements/container.vue')['default']
    Dashboard: typeof import('./components/Dashboard.vue')['default']
    Editor: typeof import('./components/editor/Editor.vue')['default']
    EditorPanel: typeof import('./components/editor/EditorPanel.vue')['default']
    EditorStatusBar: typeof import('./components/editor/EditorStatusBar.vue')['default']
    EditorToolbar: typeof import('./components/editor/EditorToolbar.vue')['default']
    Element: typeof import('./components/editor/blocks/elements/element.vue')['default']
    ElementPreview: typeof import('./components/preview/ElementPreview.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Icon: typeof import('./components/common/Icon.vue')['default']
    Message: typeof import('./components/common/Message.vue')['default']
    Preview: typeof import('./components/preview/Preview.vue')['default']
    SidebarLeft: typeof import('./components/SidebarLeft.vue')['default']
    SidebarRight: typeof import('./components/SidebarRight.vue')['default']
    Slider: typeof import('./components/editor/blocks/elements/slider.vue')['default']
    SliderPreview: typeof import('./components/preview/SliderPreview.vue')['default']
    Toolbar: typeof import('./components/Toolbar.vue')['default']
    Tree: typeof import('./components/common/Tree.vue')['default']
    TreeList: typeof import('./components/common/TreeList.vue')['default']
    UIKits: typeof import('./components/uikits/UIKits.vue')['default']
  }
}

export { }
